version: '2.1'

services:
  postgresql:
    image: postgres:9.5
    restart: always
    env_file: docker-compose.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  web_app:
    image: ubnt/ucrm-billing:latest
    restart: always
    env_file: docker-compose.env
    links:
      - postgresql:postgresql
      - elastic:elastic
      - rabbitmq:rabbitmq
    volumes:
      - ./data/ucrm:/data
    ports:
      - 8080:80
      - 8081:81
      - 8443:443
      - 2055:2055/udp
    command: "server"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  elastic:
    image: elastic/elasticsearch:6.2.4
    volumes:
      - ./data/elasticsearch6:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  rabbitmq:
    image: rabbitmq:3
    restart: always
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    hostname: ucrm-rabbitmq
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
